commandenchanter:
    sets:
        leather_set: [ 298, 299, 300, 301 ]
        chain_set: [ 302, 303, 304, 305 ]
        iron_set: [ 306, 307, 308, 309 ]
        diamond_set: [ 310, 311, 312, 313 ]
        golden_set: [ 314, 315, 316, 317 ]
        axe: [ 271, 275, 258, 286, 279 ]
        hoe: [ 290, 291, 292, 294, 293 ]
        shovel: [ 269, 273, 256, 284, 277 ]
        pickaxe: [ 270, 274, 257, 285, 278 ]
    enchants:
        protection:
            allowsets: [ leather_set, chain_set, iron_set, diamond_set, golden_set ]
            eid: 0
            maxlevel: 12
        efficiency:
            allowsets: [ axe, hoe, shovel, pickaxe ]
            eid: 32
            maxlevel: 12