commandenchanter:
    sets:
        helmet: [ 298, 302, 306, 310, 314 ]
        chestplate: [ 299, 303, 307, 311, 315 ]
        leggings: [ 300, 304, 308, 312, 316 ]
        boots: [ 301, 305, 309, 313, 317 ]
        axe: [ 271, 275, 258, 286, 279 ]
        hoe: [ 290, 291, 292, 294, 293 ]
        shovel: [ 269, 273, 256, 284, 277 ]
        pickaxe: [ 270, 274, 257, 285, 278 ]
    enchants:
        protection:
            allowsets: [ helmet, chestplate, leggings, boots ]
            eid: 0
            maxlevel: 12
        efficiency:
            allowsets: [ axe, hoe, shovel, pickaxe ]
            eid: 32
            maxlevel: 12